name = "ai-tools-directory"
main = "src/worker.js"
compatibility_date = "2026-02-18"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ai_tools_directory"
database_id = "009c88ad-92e8-48f7-8616-027b1615d1a8"
migrations_dir = "migrations"
