name = "ai-tools-directory"
pages_build_output_dir = "public"
compatibility_date = "2026-02-18"

[[d1_databases]]
binding = "DB"
database_name = "ai_tools_directory"
database_id = "009c88ad-92e8-48f7-8616-027b1615d1a8"
migrations_dir = "migrations"
